// Generated by Wrangler by running `wrangler types`

interface Env {
    ADMIN_AUTHORIZATION_TOKEN: 'ABC123'
    CLIENT_AUTHORIZATION_TOKEN: 'DEF456'
    REGION: 'auto'
    STUDIO_USER: 'admin'
    STUDIO_PASS: '123456'
    ENABLE_ALLOWLIST: 0
    ENABLE_RLS: 0
    AUTH_ALGORITHM: 'RS256'
    AUTH_JWKS_ENDPOINT: ''
    DATABASE_DURABLE_OBJECT: DurableObjectNamespace<
        import('./src/index').StarbaseDBDurableObject
    >
    /** Optional R2 bucket for storing large export files (see wrangler.toml). */
    EXPORT_R2_BUCKET?: R2Bucket
}
